(()=>{'use strict';const $=id=>document.getElementById(id);const H=20,VX=10,G=10,T=Math.sqrt(2*H/G);let time=0,running=false,frame=0,last=0;
function state(t){return {t,x:VX*t,y:Math.max(0,H-.5*G*t*t),vx:VX,vy:-G*t,v:Math.hypot(VX,G*t)}}
function stop(){running=false;cancelAnimationFrame(frame);$('play').textContent=time>=T?'↻ 重播':'▶ 播放'}
function draw(){if($('lesson').hidden)return;const canvas=$('scene'),rect=canvas.getBoundingClientRect();if(!rect.width||!rect.height)return;const dpr=devicePixelRatio||1,w=rect.width,h=rect.height;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);const scale=Math.min((w-110)/30,(h-100)/25),originX=56,ground=h-42,point=(x,y)=>[originX+x*scale,ground-y*scale];c.fillStyle='#142448';c.fillRect(0,0,w,h);c.lineWidth=1;c.strokeStyle='#ffffff0d';for(let x=0;x<=25;x+=5){const [px]=point(x,0);c.beginPath();c.moveTo(px,38);c.lineTo(px,ground);c.stroke()}for(let y=0;y<=25;y+=5){const [,py]=point(0,y);c.beginPath();c.moveTo(24,py);c.lineTo(w-20,py);c.stroke()}const [ox,oy]=point(0,H);c.fillStyle='#344966';c.fillRect(originX-32,oy,32,ground-oy);c.strokeStyle='#8a9cbb';c.beginPath();c.moveTo(20,ground);c.lineTo(w-18,ground);c.stroke();c.font='12px system-ui';c.fillStyle='#a8b9d4';for(let x=0;x<=20;x+=5){const [px]=point(x,0);c.fillText(String(x),px-4,ground+19)}c.fillText('x / m',w-50,ground+34);c.fillText('地面',w-52,ground-9);c.fillText('h = 20 m',16,oy-13);c.fillText('v₀ = 10 m/s',originX+10,oy-15);
if($('trajectory').checked){c.setLineDash([4,6]);c.strokeStyle='#7596b6';c.lineWidth=2;c.beginPath();for(let i=0;i<=100;i++){const s=state(T*i/100),p=point(s.x,s.y);i?c.lineTo(...p):c.moveTo(...p)}c.stroke();c.setLineDash([]);c.strokeStyle='#e0f5ff';c.beginPath();for(let i=0;i<=100;i++){const s=state(time*i/100),p=point(s.x,s.y);i?c.lineTo(...p):c.moveTo(...p)}c.stroke();for(let t=.5;t<time;t+=.5){const s=state(t),p=point(s.x,s.y);c.fillStyle='#91a6c5';c.beginPath();c.arc(...p,3,0,2*Math.PI);c.fill()}}
const s=state(time),[x,y]=point(s.x,s.y);function arrow(x1,y1,x2,y2,color,label){c.strokeStyle=color;c.fillStyle=color;c.lineWidth=2;c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.stroke();const a=Math.atan2(y2-y1,x2-x1);c.beginPath();c.moveTo(x2,y2);c.lineTo(x2-8*Math.cos(a-.45),y2-8*Math.sin(a-.45));c.lineTo(x2-8*Math.cos(a+.45),y2-8*Math.sin(a+.45));c.closePath();c.fill();c.font='12px system-ui';c.fillText(label,Math.min(w-88,x2+6),Math.min(h-7,y2-5))}
if($('vectors').checked){const vs=Math.min(2,scale*.4);arrow(x,y,x+VX*vs,y,'#ffbd75','vₓ = 10');if(time>.01){const vyLength=Math.abs(s.vy)*vs;/* Keep arrows inside diagram by drawing vertical vector from the ball upward to an offset endpoint when near ground is not allowed: draw at a separate anchored inset instead. */const insetX=w-88,insetY=65;c.fillStyle='#a8b9d4';c.font='12px system-ui';c.fillText('速度分解',w-110,46);arrow(insetX,insetY,insetX+VX*vs,insetY,'#ffbd75','');arrow(insetX,insetY,insetX,insetY+vyLength,'#8ae9d2','vᵧ '+s.vy.toFixed(1));c.fillStyle='#a8b9d4';c.fillText('m/s',w-72,insetY+vyLength+15)}}c.fillStyle='#ffc17d';c.beginPath();c.arc(x,y,8,0,2*Math.PI);c.fill();c.strokeStyle='#fff4dc';c.lineWidth=2;c.stroke();
$('timeline').value=time.toFixed(2);$('clock').textContent=time.toFixed(2)+' / '+T.toFixed(2)+' s';$('xValue').innerHTML=s.x.toFixed(2)+' <small>m</small>';$('yValue').innerHTML=s.y.toFixed(2)+' <small>m</small>';$('vValue').innerHTML=s.v.toFixed(2)+' <small>m/s</small>';$('phase').textContent=time>=T?'触地前瞬间':running?'运动中':time>0?'已暂停':'准备开始'}
function seek(t){stop();time=Math.max(0,Math.min(T,t));$('play').textContent=time>=T?'↻ 重播':'▶ 播放';draw()}
function play(){if(running){stop();draw();return}if(time>=T)time=0;running=true;last=performance.now();$('play').textContent='Ⅱ 暂停';function tick(now){time=Math.min(T,time+Math.min(.1,(now-last)/1000)*Number($('speed').value));last=now;if(time>=T)stop();draw();if(running)frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick)}
$('play').onclick=play;$('reset').onclick=()=>seek(0);$('step').onclick=()=>seek(Number((time+.1).toFixed(2)));$('timeline').oninput=()=>seek(Number($('timeline').value));$('trajectory').onchange=$('vectors').onchange=draw;window.addEventListener('resize',draw);document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();draw()}});
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if($('simulation').requestFullscreen)await $('simulation').requestFullscreen();else{$('simulation').scrollIntoView({block:'start'});$('fullscreen').textContent='此浏览器不支持全屏'}}catch{$('fullscreen').textContent='无法开启全屏'}};document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'退出全屏':'放大演示';draw()});
function route(){const lesson=location.hash==='#q-demo-horizontal';stop();$('lesson').hidden=!lesson;$('library').hidden=lesson;$('navLibrary').classList.toggle('active',!lesson);$('navLesson').classList.toggle('active',lesson);document.title=lesson?'平抛运动示例 · 见物动态题库':'见物 · 物理动态题库';window.scrollTo(0,0);draw()}window.addEventListener('hashchange',route);route();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const tool={name:'show_physics_model_at_time',title:'查看物理模型的指定时刻',description:'打开平抛示例并暂停在指定的0至2秒时刻，返回位置和速度。',inputSchema:{type:'object',properties:{time:{type:'number',minimum:0,maximum:2}},required:['time'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input.time!=='number'||!Number.isFinite(input.time)||input.time<0||input.time>T||Object.keys(input).some(k=>k!=='time'))throw new Error('time must be a finite number from 0 to 2 seconds');location.hash='#q-demo-horizontal';route();seek(input.time);return {model:'demo-horizontal',...state(time)}}};try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}

})();
